name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      env:
        DOCKER_TAG: $(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag atlassian-sdk:$DOCKER_TAG
    - name: Test the Docker image
      run: docker run atlassian-sdk:$DOCKER_TAG
    - name: Deploy the Docker image
      run: echo "TODO"
